#!/usr/bin/env python
import sys
from subprocess import Popen, PIPE

IF='eth0'

def get_stat(interface):
	p = Popen(['bwm-ng', '-o', 'csv', '-c', '1'], stdout=PIPE)
	for line in p.communicate()[0].split('\n'):
		if 'eth0' in line:
			return line.split(';')[3]

def main():
	while True:
		print get_stat(IF)
		sys.stdout.flush()

# | grapher.py -s -
if __name__ == '__main__':
	try:
		main()
	except KeyboardInterrupt:
		print ''
