#!/usr/bin/env python

import sys
from subprocess import Popen, PIPE

command = sys.argv[1:]

if not command:
    sys.stderr.write('usage: chronic COMMAND...\n'
                     '(like chronic from moreutils)\n')
    sys.exit(1)

p = Popen(command, stdout=PIPE, stderr=PIPE)
out, err = p.communicate()

if p.returncode != 0:
    sys.stdout.write(out)
    sys.stderr.write(err)
    sys.exit(p.returncode)
