#!/usr/bin/env python3

"""
Prompt the user for a password and print the result on stdout.

The password prompt goes to stderr. Input is read from stdin and terminated by
a newline. The result is written with no newline to stdout.
"""

import getpass
import optparse
import sys

p = optparse.OptionParser(usage='usage: %prog [PROMPT]' + __doc__.rstrip('\n'))
p.add_option('-n', '--newline', help='print trailing newline',
             action='store_true')
opts, args = p.parse_args()

if args:
    prompt = ' '.join(args)
else:
    prompt = 'Password: '

out_stream = sys.stdout

try:
    pw = getpass.getpass(prompt)
except EOFError:
    sys.exit(1)
except KeyboardInterrupt:
    sys.exit(2)

out_stream.write(pw)
if opts.newline:
    out_stream.write('\n')
