#!/usr/bin/env ruby
# Andy's Split: split lines in streams by separator.

def usage
  STDERR.puts <<-EOM
usage: #{File.basename($0)} SEPARATOR [FILE...]

Split each line in each FILE by SEPARATOR. If no FILE is not given, read from
standard input.
  EOM
end

def main(sep, *streams)
  streams.each do |stream|
    stream.each_line do |line|
      line.chomp.split(sep, -1).each do |part|
        puts part
      end
    end
  end
end

if ARGV.empty?
  usage
  exit 1
end

sep = ARGV.shift

if ARGV.empty?
  streams = [STDIN]
else
  streams = ARGV.map {|filename|
    if filename == '-'
      STDIN
    else
      File.open(filename, 'r')
    end
  }
end

main(sep, *streams)
