#!/bin/bash

# Adapted from https://unix.stackexchange.com/a/724963/5097

clipboard="${clipboard-1}"

set -euo pipefail

# Call gdbus to run color picker widget
output="$(gdbus call --session --dest org.gnome.Shell.Screenshot --object-path /org/gnome/Shell/Screenshot --method org.gnome.Shell.Screenshot.PickColor)"

# assign floating point values (0.0-1.0) to array of length 3
readarray -t colors < <(grep -o "[0-9\.]*" <<< "$output")

# Convert to 255-based RGB format
for ((i = 0; i < ${#colors[@]}; i++)); do
    colors[$i]="$(printf '%.0f' "$(echo "${colors[$i]} * 255" | bc)")"
done

echo "RGB: ${colors[0]} ${colors[1]} ${colors[2]}"
as_hex="$(printf "#%02x%02x%02x" "${colors[0]}" "${colors[1]}" "${colors[2]}")"
echo "HEX: $as_hex"

if [ -n "$clipboard" ]; then
    echo -n "$as_hex" | xclip -selection clipboard
    echo "(copied to clipboard)"
fi
