#!/usr/bin/env python
import sys, time

if len(sys.argv) > 1:
	sec = float(sys.argv[1])
else:
	sec = 1

try:
	while True:
		sys.stdout.write(".")
		sys.stdout.flush()
		time.sleep(sec)
except KeyboardInterrupt:
	print ""
