#!/bin/sh
set -e

interval=1

usage() {
    cat >&2 <<EOM
usage: $(basename "$0") [DELAY]

Print infinite '.' characters to stderr.
EOM
}

if [ $# -gt 0 ]; then
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        *)
            interval="$1"
    esac
fi

while true; do
    echo >&2 -n '.'
    sleep "$interval"
done
