#!/bin/sh
set -eu

usage() {
    cat >&2 <<EOM
usage: $0 PATH

Make a request to the EC2 instance metadata service using IMDSv2.

For example:
    $0 /latest/meta-data/
    $0 /latest/meta-data/ami-id
    $0 /latest/meta-data/instance-id
    $0 /latest/meta-data/public-ipv4

EOM
}

if [ $# -lt 1 ]; then
    usage
    exit 1
fi

token="$(curl -sSf -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 3600")"
curl -sSf -H "X-aws-ec2-metadata-token: $token" "http://169.254.169.254/$1"
echo
