#!/usr/bin/env python
# coding=utf-8

import sys

ALIASES = {
    'fliptable': 'flip',
    'table': 'flip',
}

ALL_EMOJI = {
    'unimpressed': 'ಠ_ಠ',
    'shrug': '¯\_(ツ)_/¯',
    'flip': '(╯°□°)╯︵ ┻━┻',
    'tm': '™',

    'cat': '(^._.^)ﾉ',
    'catface': '(^人^)',
    'sideeye': '(¬_¬)',

    'o_O': 'ミ●﹏☉ミ',
    'o_O2': '(⊙_◎)',
    'o_O3': '(⊙﹏⊙✿)',

    'dance1': '┌(・。・)┘♪',
    'dance2': '└(・。・)┐♪',
    'dance3': '♪┌(˘⌣˘)ʃ',

    'scared': '(´･_･`)',

    'flowerhappy': '(✿◠‿◠)',
    'hug': '⊂((・▽・))⊃',

    'facepalm': '(>_<)',
}
def emoji_for(word):
    word = ALIASES.get(word, word)
    return ALL_EMOJI[word]

if len(sys.argv) > 1:
    word = sys.argv[1]
    try:
        print emoji_for(word)
    except KeyError:
        print 'Unknown emoji: %r' % word
        sys.exit(1)
else:
    for name, emoji in ALL_EMOJI.iteritems():
        print name + ':', emoji

