#!/bin/sh

set -eu

run() {
    echo >&2 "+ $*"
    "$@"
}

if [ $# -lt 2 ]; then
    echo >&2 "usage: $(basename "$0") OUTPUT INPUT..."
    exit 1
fi

output="$1"
shift

# use temp file instead of <() due to cwd nonsense from ffmpeg
tmpf="$(mktemp .ffmpeg-concat.XXXXXX)"
trap "rm -rf '$tmpf'" EXIT

printf "file '%s'\n" "$@" > "$tmpf"

run ffmpeg -f concat -i "$tmpf" -c copy "$output"
