#!/bin/bash

set -euo pipefail

run() {
    echo >&2 "+ $*"
    "$@"
}

if [ $# -lt 2 ] || [ $# -gt 2 ]; then
    cat >&2 <<EOM
usage: $(basename "$0") INPUT OUTPUT

Convert HDR video to standard def using zscale tone mapping.

I cargo culted these options, so I have no idea if this is the recommended way
to do this. The video snobs on the internet suggest just going back in time and
recording in SDR instead as the better way, or going forward in time and using
a player that supports HDR instead.

Original purpose: convert HDR iOS videos to SDR for use with 1SE on Android.

For example:

    $(basename "$0") IMG_1234.MOV out.mp4

EOM
    exit 1
fi

input="$1"
output="$2"

run ffmpeg -i "$input" -vf zscale=t=linear:npl=100,format=gbrpf32le,zscale=p=bt709,tonemap=hable:desat=0,zscale=t=bt709:m=bt709:r=tv,format=yuv420p "$output"

echo "Successfully wrote $output"
