#!/bin/sh
set -eu

usage() {
    cat >&2 <<EOM
usage: $(basename "$0") INFILE START_TIME END_TIME OUTFILE

For example, to take a 1 minute clip of a video starting around minute 37:
    $(basename "$0") video.mp4 00:37:21 00:38:21 clip.mp4

Other ffmpeg examples:
    ffmpeg -i video.mp4 -ss 00:37:21 -to 00:38:21 -c copy clip-1min.mp4
    ffmpeg -i video.mp4 -ss 00:37:21 -t 01:00 -c copy clip-1min.mp4

EOM
}

if [ $# -ne 4 ]; then
    usage
    exit 1
fi

set -x
# not sure if '-async 1' is helpful or not
# https://stackoverflow.com/questions/18444194/cutting-the-videos-based-on-start-and-end-time-using-ffmpeg
ffmpeg -i "$1" -ss "$2" -to "$3" -c copy "$4"
