#!/bin/bash
set -euo pipefail

# Note: this may be superseded by the function version in .bash_aliases

run() {
    echo >&2 "+ $*"
    "$@"
}

git-main-branch() {
    local ret
    git rev-parse --verify --quiet master >/dev/null && ret=$? || ret=$?

    case "$ret" in
        0)
            echo master
            return
            ;;
        1)
            # pass
            ;;
        *)
            return "$ret"
            ;;
    esac

    if git rev-parse --verify --quiet main >/dev/null; then
        echo main
    else
        echo >&2 "Neither master nor main exists"
        return 1
    fi
}

# check out the master/main branch
git-checkout-main() {
    local branch
    branch="$(git-main-branch)" || return $?
    run git checkout "$branch"
}

git-checkout-main
