#!/bin/bash
set -euo pipefail

# Note: this may be superseded by the function version in .bash_aliases

run() {
    echo >&2 "+ $*"
    "$@"
}

# Determine the main/master branch and echo its name.
git-main-branch() {
    local ret
    git rev-parse --verify --quiet main >/dev/null && ret=$? || ret=$?

    case "$ret" in
        0)
            echo main
            return
            ;;
        1)
            # pass
            ;;
        *)
            # probably not a git repo / some other error
            return "$ret"
            ;;
    esac

    if git rev-parse --verify --quiet master >/dev/null; then
        echo master
        return
    fi

    local head_ref
    if head_ref=$(git rev-parse --verify --quiet --abbrev-ref origin/HEAD)
    then
        echo "$head_ref" | cut -d/ -f2
        return
    fi

    echo >&2 "Error: could not determine the default branch name"
    echo >&2 "* Neither master nor main exists"
    echo >&2 "* Also could not determine default branch from origin/HEAD"
    return 1
}

# check out the master/main branch
git-checkout-main() {
    local branch
    branch="$(git-main-branch)" || return $?
    run git checkout "$branch"
}

git-checkout-main
