#!/bin/bash
set -euo pipefail

run() {
    echo >&2 "+ $*"
    "$@"
}

# usage: prompt_yn [PROMPT]
# Prompt the user for a yes/no response.
#
# Exit codes:
#   0: user entered yes
#   2: STDIN is not a TTY
#   10: user entered no
#
prompt_yn() {
    local prompt ans
    if [ $# -ge 1 ]; then
        prompt="$1"
    else
        prompt="Continue?"
    fi

    if [ ! -t 0 ]; then
        echo >&2 "$prompt [y/n]"
        echo >&2 "prompt_yn: error: stdin is not a TTY!"
        return 2
    fi

    while true; do
        read -r -p "$prompt [y/n] " ans
        case "$ans" in
            Y|y|yes|YES|Yes)
                return
                ;;
            N|n|no|NO|No)
                return 10
                ;;
        esac
    done
}

current_branch="$(git branch --show-current)"
nothing_to_do=1

for branch in $(git branch --format='%(refname:short)' --merged); do
    case "$branch" in
        master|main)       continue ;;
        stages/*)          continue ;;
        "$current_branch") continue ;;
    esac

    nothing_to_do=
    if prompt_yn "Delete '$branch'?"; then
        run git branch -d "$branch"
    fi
done

if [ -n "$nothing_to_do" ]; then
    echo "Nothing to do"
else
    echo "Done"
fi
