#!/bin/bash
set -euo pipefail

run() {
    echo >&2 "+ $*"
    "$@"
}


# rename master to main locally
run git branch -m master main

# set remote tracking
run git push -u origin main

# repoint HEAD ref for remote
run git remote set-head origin -a

echo "Optional, now run: git push origin --delete master"
