#!/bin/bash
set -eux
sudo aptitude install libncurses5-dev libreadline6-dev
cd ~
git clone git@github.com:sstephenson/rbenv.git .rbenv
cd .rbenv/plugins
git clone git@github.com:sstephenson/ruby-build.git
