#!/bin/sh

set -eu

usage() {
  cat >&2 <<EOM
usage: $(basename "$0") FILE...

Remove EXIF location data from JPEG image FILEs.
EOM
}

if [ $# -lt 1 ]; then
  usage
  exit 1
fi

run() {
  echo >&2 "+ $*"
  "$@"
}

for i in "$@"; do
  run exiftool -gps:all= "$i"
done
