#!/usr/bin/env -S uv run --script
#
# /// script
# requires-python = ">= 3.11"
# dependencies = ["pyjwt"]
# ///

import base64
import json
import sys

import jwt

sys.stderr.write("Reading JWT on stdin...\n")

data = sys.stdin.read()

sys.stderr.write(f"JWT to decode: {data!r}\n")
sys.stderr.flush()

parts = jwt.decode_complete(data, options={'verify_signature': False})

print("\nDecoded JWT:", file=sys.stderr)
out = {}
out["header"] = parts["header"]
out["payload"] = parts["payload"]
out["signature_b64"] = base64.b64encode(parts["signature"]).decode('utf-8')

print(json.dumps(out, indent=2))
