#!/bin/sh

dryrun=
if [ "$1" = "-n" ]; then
	dryrun=1
	shift
fi

if [ -z "$1" -o "$1" = "-h" ]; then
	echo "$(basename "$0") [-n] MINS"
	echo "Remove all files from ~/.thumbnails/ newer than MINS minutes."
	exit 1
fi

mins=$1

if [ -n "$dryrun" ]; then
	find ~/.thumbnails/ -type f -mmin "-$mins" -print
else
	find ~/.thumbnails/ -type f -mmin "-$mins" -exec shred -uvz {} \;
fi
