#!/bin/sh
set -u

if [ $# -lt 1 ]; then
    echo "$(basename "$0") URL"
    exit 1
fi

sleep=0
echo "testing \"$*\""
echo "sleep: $sleep"

while true; do
    curl -sS -f "$@" > /dev/null && echo -n .
    sleep $sleep
done
