[tasks.test]
description = "Run test suite"
run = "bats ./test"

[tasks.install_dev_deps]
description = "Install testing/dev dependencies"
run = """
set -eux
if ! which bats; then
    sudo apt install -y bats bats-assert
fi
"""

[tasks.install_dev_deps_macos]
description = "Install testing/dev dependencies on macOS"
run = """
set -eux
brew install bats-core
brew tap bats-core/bats-core
brew install bats-assert bats-support
set +x

echo "Warning: you must set 'export BATS_LIB_PATH=$(brew --prefix)/lib'"
"""
