#!/bin/bash
# dynamic dns client for noip.com

set -eu
set -o pipefail

log() {
    echo >&2 "$@"
}
logrun() {
    log "+ $@"
    "$@"
}
basename="$(basename "$0")"
slog() {
    log "$@"
    logger -t "$basename" <<< "$@"
}

usage() {
    cat >&2 <<EOM
usage: $(basename "$0") [options] [ADDRESS]

Configuration values are taken from ~/.noiprc.

If ADDRESS is given, change the DDNS record to ADDRESS regardless of what our
public IP address seems to be.

options:

    -h, --help    Show this message
    --force       Force an update even if we think none is needed
    --frob        Twiddle the DDNS record to prevent expiry

EOM
}

force_update=
frob_update=
while [ $# -gt 0 ] && [[ $1 = -* ]]; do
    case "$1" in
        --force)
            force_update=1
            shift
            ;;
        --frob)
            # --frob implies --force
            frob_update=1
            force_update=1
            shift
            ;;
        -h,--help)
            usage
            exit 0
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

force_addr=
if [ $# -gt 1 ]; then
    usage
    exit 1
elif [ $# -eq 1 ]; then
    force_addr="$1"
    shift
fi

# duplicate stdout/stderr to syslog
#exec 1> >(tee -a /dev/fd/1 | logger -t "$(basename "$0")")
#exec 2> >(tee -a /dev/fd/2 | logger -t "$(basename "$0")")

# add fd 3 for printing stuff with a prefix
exec 3> >(sed 's/^/>>> /')

trap "echo >&2 ERROR" EXIT

slog "Starting up"

NOIP_RCFILE="$HOME/.noiprc"
. "$NOIP_RCFILE"

if [ -n "$frob_update" ]; then
    slog "Performing frob update of $NOIP_HOSTNAME"
    "$0" --force 192.0.2.1
    slog "Proceeding with frob back to normal address"
fi

log "hostname: $NOIP_HOSTNAME"
log "noip.com username: $NOIP_USERNAME"
log "noip.com password: $(sed 's/./*/g' <<< "$NOIP_PASSWORD")"

pub_addr="$(logrun curl -Ssf https://agb.me/ip/ | tee -a /dev/fd/3)"
dns_addr="$(logrun dig +short "$NOIP_HOSTNAME" | tee -a /dev/fd/3)"

log "Public IP address from HTTP: $pub_addr"
log "Public IP address from DNS:  $dns_addr"

if [ -n "$force_addr" ]; then
    log "Overriding public IP address with '$force_addr'"
    pub_addr="$force_addr"
fi

NOIP_HOST="${NOIP_HOST:-dynupdate.no-ip.com}"
NOIP_ENDPOINT="https://$NOIP_HOST/nic/update"


if [ "$pub_addr" != "$dns_addr" ]; then
    slog "Updating $NOIP_HOSTNAME to $pub_addr (was $dns_addr)"
    update=1
elif [ -n "$force_update" ]; then
    slog "Forcing update even though $NOIP_HOSTNAME is already $pub_addr"
    update=1
else
    update=
fi

if [ -n "$update" ]; then
    netrc="machine $NOIP_HOST login $NOIP_USERNAME password $NOIP_PASSWORD"
    logrun curl -sSf --netrc-file <(echo "$netrc") \
        "$NOIP_ENDPOINT?hostname=$NOIP_HOSTNAME&myip=$pub_addr" >&3
    echo >&3
else
    slog "No update to $NOIP_HOSTNAME needed"
fi

# close fd 3 to flush output
3>&-

slog "All done"
trap - EXIT
