#!/bin/bash

date=$(date "+%F")
day=$(date "+%a")
ext=txt

case $day in
	Mon | Wed | Fri)
		dstamp=$date.${day:0:1};;
	*)
		dstamp=$date.${day:0:2};;
esac

if [ $# -ge 1 ]; then
    label="$1"
    fname="$label.$dstamp.$ext"
else
    fname="$dstamp.$ext"
fi

"${EDITOR-vim}" "$fname"

#case "$1" in
#	gedit)
#		cmd=gedit;;
#	pyroom)
#		cmd=pyroom;;
#	vim)
#		cmd=vim;;
#	lyx)
#		cmd=lyx
#		ext=lyx;;
#	*)
#		cmd=vim;;
#esac
#
#$cmd $dstamp.$ext
