#!/usr/bin/env python
import sys

def check_readable(filename):
    try:
        open(filename, 'r')
    except IOError as err:
        sys.stderr.write(err.strerror + ': ' + repr(err.filename) + "\n")
        sys.exit(err.errno)

files = sys.argv[1:]

if not files:
    sys.stderr.write("usage: readable FILE...\n")
    sys.exit(1)

for filename in sys.argv[1:]:
    check_readable(filename)
