#!/bin/bash
# v1.2
set -e
set -o nounset

list_installed() {
    # shellcheck disable=SC2016
    dpkg-query -W -f '${Package}\t${Status}\n' | \
        sed -n 's/\tinstall ok installed$//p' | grep "$1"
}

running="$(uname -r | cut -d'-' -f 1-2)"
latest="$(list_installed 'linux-image-[0-9]\+' | \
          sort -n | tail -1 | cut -d'-' -f 3-4)"

pkgs="$(grep -v -h -e "$latest" -e "$running" \
    <(list_installed 'linux-image-[0-9]\+') \
    <(list_installed 'linux-headers-[0-9]\+'))"

echo "Packages to remove:"
echo "$pkgs"
echo ""

read -s -n 1 -p "Press any key to continue..."
echo -e "\n"

set -x
# shellcheck disable=SC2086
sudo apt purge $pkgs
