#!/bin/bash
# v1.1
set -e
set -o nounset

# Get version name and strip off component after second hyphen.
full_version="$(uname -r)"
version="$(echo "$full_version" | cut -d'-' -f 1-2)"
echo "Running kernel: $version ($full_version)"

pattern='~ilinux-(image|headers)-[0-9].* !'"$version"

echo "Packages to remove:"
aptitude search "$pattern"

read -s -n 1 -p "Press any key to continue..."
echo -e "\n"

set -x
sudo aptitude purge "$pattern"

