#!/bin/bash

set -eu

usage() {
    cat >&2 <<EOM
usage: $(basename "$0") NUMBER

Look up RFC \$NUMBER on the IETF website.
EOM
}

run() {
    echo >&2 "+ $*"
    "$@"
}

if [ $# -lt 1 ]; then
    usage
    exit 1
fi

run_pager() {
    if which sensible-pager >/dev/null 2>&1; then
        run sensible-pager "$@"
    else
        run less "$@"
    fi
}

run curl -sSf "https://tools.ietf.org/rfc/rfc${1}.txt" | run_pager
