#!/bin/bash
set -eu

usage() {
    cat >&2 <<EOM
usage: $(basename "$0") FILE DEST_DIR

Copy FILE to DEST_DIR, splitting it into < 4 GiB chunks appropriate for a
limited size filesystem like FAT32.
EOM
}

case "$OSTYPE" in
    linux*)
        split="split"
        ;;
    darwin*)
        split="gsplit"
        ;;
    *)
        echo >&2 "Error: unknown OS $OSTYPE"
        exit 1
        ;;
esac

if [ $# -lt 2 ]; then
    usage
    exit 1
fi

src="$1"
dst="$2"

basename="$(basename "$src")"

set -x
exec "$split" -b 4294967295 --verbose "$src" "$dst/$basename-"
