#!/bin/sh
set -eu
case "$(hostname -s)" in
    coruscant)
        uuid=c49376a4-98ad-400c-9600-ffd8cbd2cceb
        ;;
    hoth)
        uuid=c7b9af5a-ef6c-4a86-98ee-3370c557e054
        ;;
    wisp)
        uuid=f4b6fe62-6737-47aa-bbb9-f763c58eb711
        ;;
    *)
        echo >&2 "Unknown host: $(hostname -s)"
        exit 1
        ;;
esac

if [ $# -gt 0 ] && [ "$1" = "down" ]; then
    set -x
    exec nmcli con down uuid "$uuid"
else
    set -x
    nmcli con up uuid "$uuid"
    exec ssh dev8
fi
