#!/usr/bin/env perl
use strict;
use warnings;
use Scalar::Util;

my $sum = 0;

while (<>) {
    chomp $_;
    unless (Scalar::Util::looks_like_number($_)) {
        print "Invalid number: " . $_ . "\n";
        exit 1;
    }
    $sum += $_;
}

print $sum;
print "\n";
