#!/usr/bin/env python

import sys
import time
from datetime import datetime

def main(args):
    local = True
    try:
        if args[0] == '-u':
            local = False
            args = args[1:]
    except IndexError:
        pass

    if len(args) < 1:
        print 'usage: timestamp [-u] UNIX_STAMP [FORMAT]'
        print ''
        print 'Convert UNIX_STAMP into a date string according to FORMAT.'
        print 'If -u is given, print the time in UTC.'
        return 1

    if '.' in args[0]:
        stamp = float(args[0])
        tformat = '%F %R:%S.%f'
    else:
        stamp = int(args[0])
        tformat = '%F %R:%S'
    default_format = True

    if len(args) > 1:
        tformat = args[1]
        default_format = False

    if local:
        t = datetime.fromtimestamp(stamp)
        tzname = time.strftime('%Z')
    else:
        t = datetime.utcfromtimestamp(stamp)
        tzname = 'UTC'

    sys.stdout.write(t.strftime(tformat))
    if default_format:
        sys.stdout.write(' ' + tzname)
    sys.stdout.write('\n')

    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
