#!/usr/bin/env python

import optparse
import sys
import time
from datetime import datetime

VERSION = '1.2'

def main():
    usage = '''%prog [options] UNIX_STAMP...

Convert each UNIX_STAMP into a date string according to strftime FMT.
'''.rstrip()
    p = optparse.OptionParser(usage=usage, version = '%prog ' + VERSION)
    p.add_option('-u', '--utc', dest='local', action='store_false',
                 help='print time in UTC', default=True)

    p.add_option('-f', '--format', help='strftime format', dest='tformat',
                 metavar='FMT')
    p.add_option('-s', '--stamp', help='print current timestamp', dest='stamp',
                 action='store_true')
    p.add_option('-i', '--integer', help='print integer times',
                 dest='integer', action='store_true')

    opts, args = p.parse_args()

    if opts.stamp:
        print_current_timestamp(integer=opts.integer)
        return 0

    if not args:
        p.print_help()
        return 1

    for stamp in args:
        print_stamp_as_string(stamp, opts)

    return 0

def print_stamp_as_string(stamp, opts):

    if '.' in stamp:
        stamp = float(stamp)
        if opts.integer:
            tformat = '%F %R:%S'
        else:
            tformat = '%F %R:%S.%f'
    else:
        stamp = int(stamp)
        tformat = '%F %R:%S'

    if opts.tformat:
        default_format = False
        tformat = opts.tformat
    else:
        default_format = True

    if opts.local:
        t = datetime.fromtimestamp(stamp)
        tzname = time.strftime('%Z')
    else:
        t = datetime.utcfromtimestamp(stamp)
        tzname = 'UTC'

    sys.stdout.write(t.strftime(tformat))
    if default_format:
        sys.stdout.write(' ' + tzname)
    sys.stdout.write('\n')

def print_current_timestamp(integer=False):
    if integer:
        fmt = '%s'
    else:
        fmt = '%s.%f'
    sys.stdout.write(datetime.now().strftime(fmt) + '\n')

if __name__ == '__main__':
    sys.exit(main())
