#!/usr/bin/env python3
"""
usage: total [FILE...]

Sum numbers given on stdin or in files and print the total.

For example:

    $ seq 1 10 | total
    55
"""

import decimal
import fileinput
import sys


def usage():
    print(__doc__.strip())


if sys.stdin.isatty() and len(sys.argv) < 2:
    usage()
    sys.exit(1)

total = 0

for line in fileinput.input():
    line = line.strip()
    if not line:
        continue

    # try parsing as int, then Decimal (don't bother with float)
    try:
        n = int(line)
    except ValueError:
        try:
            n = decimal.Decimal(line)
        except decimal.InvalidOperation as err:
            if not err.args[0][0] == decimal.ConversionSyntax:
                raise
            sys.stderr.write(f"Invalid number: {line!r}\n")
            sys.exit(2)

    total += n

print(total)
