#!/bin/sh
set -eu

# We want --no-passthrough because vimcat has some braindead behavior with
# fifos that results in deadlock on linux for certain inputs like `man timeout`

vimpager --no-passthrough -c \
    "set ft=man nomod nomodifiable | let &titlestring=\"man \" . \$MAN_PN" "$@" \
    || exec less \
    || exec cat
