#!/bin/sh
set -eu
if [ $# -ge 1 ]; then
    host=$1
else
    host=lambda
fi

case "$host" in
    eggplant)
        set -x
        ssh eggplant '/usr/sbin/wol -i 192.168.1.255 00:1f:d0:23:c6:48;
/usr/sbin/wol -i 192.168.1.255 00:1f:d0:23:c6:89'
        ;;
    local)
        set -x
        wakeonlan 00:1f:d0:23:c6:48; wakeonlan 00:1f:d0:23:c6:89
        ;;
    *)
        set -x
        ssh "$host" 'wakeonlan 00:1f:d0:23:c6:48; wakeonlan 00:1f:d0:23:c6:89'
        ;;
esac
