#!/bin/sh
set -eux
if [ $# -eq 0 ]; then
    ssh eggplant '/usr/sbin/wol -i 192.168.1.255 00:1f:d0:23:c6:48;
/usr/sbin/wol -i 192.168.1.255 00:1f:d0:23:c6:89'
else
    ssh "$1" 'wakeonlan 00:1f:d0:23:c6:48; wakeonlan 00:1f:d0:23:c6:89'
fi
