#!/bin/sh
set -eu

# env variables are assumed to be set in the init script

create_userdirs() {
    uid_min="$(grep ^UID_MIN /etc/login.defs | awk '{ print $NF }')"
    uid_max="$(grep ^UID_MAX /etc/login.defs | awk '{ print $NF }')"
    if [ -z "$uid_min" -o -z "$uid_max" ]; then
        echo >&2 "Failed to find UID_MIN and UID_MAX"
        exit 4
    fi

    getent passwd | while read line; do
        uid="$(echo "$line" | cut -f3 -d:)"
        if [ "$uid" -ge "$uid_min" -a "$uid" -le "$uid_max" ]; then
            name="$(echo "$line" | cut -f1 -d:)"
            mkdir -m 0700 "$mount/$name"
            chown "$name:" "$mount/$name"
        fi
    done
}

if [ $# -lt 1 ]; then
    echo "usage: $0 MOUNTPOINT"
    exit 1
fi

mount="$1"

create_userdirs
