#!/bin/sh
set -eu

# mountpoint settings
mount=/mnt/ramdisk
mount_chown=root:
mount_chmod=0755

# volume group and logical volume name
vgname=ramdisk
lvname=main

# number of devices out of /dev/ramN to use
ndisks=1

PATH=/sbin:/bin:/usr/sbin:/usr/bin

usage() {
    echo "Usage: $0 {start|stop|status}"
}

do_start() {
    if lvdisplay "$vgname/$lvname" >/dev/null 2>&1; then
        echo >&2 "$vgname/$lvname already exists!"
        exit 1
    fi

    devs="$(for i in $(seq 0 $(($ndisks - 1))); do echo /dev/ram$i; done)"

    for dev in $devs; do
        pvcreate "$dev"
    done

    vgcreate "$vgname" "$devs"

    lvcreate -n "$lvname" -l 100%FREE "$vgname"

    mke2fs -q -m 0 "/dev/$vgname/$lvname"

    mount "/dev/$vgname/$lvname" "$mount"
    chown "$mount_chown" "$mount"
    chmod "$mount_chmod" "$mount"

    run-parts /etc/ramdisk.d/
}

do_stop() {
    umount "$mount"
}

do_status() {
    vgdisplay "$vgname"
    lvdisplay "$vgname/$lvname"
    df -Ph "$mount"
}

if [ $# -lt 1 ]; then
    usage
    exit 3
fi

case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    status)
        do_status
        ;;
    *)
        usage
        exit 3
        ;;
esac

exit 0
