#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:          mount-ramdisk
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Create ramdisk at boot
# Description:       Create and mount a ramdisk using ramfs.
### END INIT INFO

# mountpoint settings
mount=/mnt/ramdisk
mount_chown=root:
mount_chmod=0755

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

usage() {
    log_action_msg "Usage: $0 {start|stop|restart|status}"
}

do_start() {
    if grep "$mount" /proc/mounts; then
        echo >&2 "$mount is already mounted!"
        exit 1
    fi

    mount -t ramfs myramdisk "$mount"
    chown "$mount_chown" "$mount"
    chmod "$mount_chmod" "$mount"

    run-parts -a "$mount" /etc/ramdisk.d
}

do_stop() {
    if [ -e "$mount" ]; then
        umount "$mount"
    fi
}

do_status() {
    df -Ph "$mount"
}

trap "log_action_end_msg 1" EXIT

case "$1" in
    start)
        log_action_begin_msg "Creating ramdisk"
        do_start
        ;;
    stop)
        log_action_begin_msg "Removing ramdisk"
        do_stop
        ;;
    restart|reload|force-reload)
        do_stop || true
        do_start
        ;;
    status)
        log_action_begin_msg "Getting ramdisk details"
        do_status
        ;;
    *)
        usage
        trap - EXIT
        exit 3
        ;;
esac

trap - EXIT
log_end_msg 0
exit 0
