#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:          mount-ramdisk
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Create ramdisk at boot
# Description:       Create and mount a ramdisk on LVM out of /dev/ramN.
### END INIT INFO

# mountpoint settings
mount=/mnt/ramdisk
mount_chown=root:
mount_chmod=0755

# volume group and logical volume name
vgname=ramdisk
lvname=main

# number of devices out of /dev/ramN to use
ndisks=1

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

usage() {
    log_action_msg "Usage: $0 {start|stop|restart|status}"
}

do_start() {
    if lvdisplay "$vgname/$lvname" >/dev/null 2>&1; then
        echo >&2 "$vgname/$lvname already exists!"
        exit 1
    fi

    devs="$(for i in $(seq 0 $(($ndisks - 1))); do echo /dev/ram$i; done)"

    for dev in $devs; do
        pvcreate "$dev" >/dev/null
    done

    vgcreate "$vgname" "$devs" >/dev/null

    lvcreate -n "$lvname" -l 100%FREE "$vgname" >/dev/null

    mke2fs -q -m 0 "/dev/$vgname/$lvname"

    mount "/dev/$vgname/$lvname" "$mount"
    chown "$mount_chown" "$mount"
    chmod "$mount_chmod" "$mount"

    run-parts -a "$mount" /etc/ramdisk.d
}

do_stop() {
    umount "$mount"
    lvchange -an "$vgname/$lvname"
    lvremove "$vgname/$lvname" >/dev/null
    vgremove "$vgname" >/dev/null
}

do_status() {
    vgdisplay "$vgname"
    lvdisplay "$vgname/$lvname"
    df -Ph "$mount"
}

trap "log_action_end_msg 1" EXIT

case "$1" in
    start)
        log_action_begin_msg "Creating ramdisk"
        do_start
        ;;
    stop)
        log_action_begin_msg "Removing ramdisk"
        do_stop
        ;;
    restart|reload|force-reload)
        do_stop || true
        do_start
        ;;
    status)
        log_action_begin_msg "Getting ramdisk details"
        do_status
        ;;
    *)
        usage
        trap - EXIT
        exit 3
        ;;
esac

trap - EXIT
log_end_msg 0
exit 0
